
" Override default options
set nocompatible	" we want vim's features, not stupid vi compatiblity
set ruler		" shows ruler at the bottom of the screen
set bs=2		" allow backspacing over everything in insert mode
set tabstop=4		" Set tabs to 4 spaces
set autoindent		" we want to autoindent
set sts=4 sw=4 ts=4 noet
set number	" to show line numbers
set wrap	" enable line wrapping
set nocp
set showcmd		" Show (partial) command in status line
set hlsearch		" Switch on syntax highlighting.
set incsearch		" show matches on the fly
set ignorecase		" for pattern machine
set smartcase		" Except when a mix of case is given
set exrc
set secure

set swapsync=sync	" the swap is synced with sync, not fsync
set updatecount=20	" Number of characters typed before doing an update
set updatetime=500	" Number of milliseconds before doing an update
set history=100		" Number of history commands to remember
set viminfo='50,\"200	" read/write a .viminfo file, remember filemarks for 50
			" files and store 200 lines of registers

if has("mouse")
"	set mouse=a
endif

runtime! ftplugin/man.vim

if has("filetype")
	filetype plugin on
endif

if has("autocmd")
	so ~/.shattings/vim/plist.vim
	so ~/.shattings/vim/autocmd.vim
endif

if has("syntax")
	let c_space_errors=1 " make blank spaces at EOL red
endif

"set clipboard=unnamed

so ~/.shattings/vim/clipboard.vim

" For debugging
"set verbose=9

" If bash is called sh on the system, define this
"let bash_is_sh=1

" Suffixes that get lower priority when doing tab completion for filenames.
" These are files we are not likely to want to edit or read.
set suffixes=.bak,~,.swp,.o,.info,.aux,.log,.dvi,.bbl,.blg,.brf,.cb,.ind,.idx,.ilg,.inx,.out,.toc

"
" Key mappings
"

" Key mappings for par (text reformatting)
"vmap  !par -w76 -gjq -dh -p3
"vmap X !par -w76 -gjq -p2 -dh<CR>
"vmap F !par -w76 -gjq<CR>
"vmap f !par -w80<CR>
"imap  :set invpaste<CR>a
"map  :set invpaste<CR>o

" So what, I can't type...
nmap :W :w
nmap :X :x
nmap :Q :q

nnoremap ,mdfmt :silent :%!mdfmt<CR>

" Call the external spell module (with uses ispell)
" so /etc/vim/vimspell.vim

" Enable and disable highlighted spell checking
"map <F10> :so /etc/vim/engspchk.vim<CR>
"map <F12> :hi link BadWord none<CR>

" Move cursor by lines on *screen* instead of lines in *file*
nnoremap j gj
nnoremap k gk
vnoremap j gj
vnoremap k gk
nnoremap <Down> gj
nnoremap <Up> gk
vnoremap <Down> gj
vnoremap <Up> gk
inoremap <Down> <C-o>gj
inoremap <Up> <C-o>gk

"if &term =~ "xterm-debian" || &term =~ "xterm-xfree86"
"  set t_Co=16
"  set t_Sf=[3%dm
"  set t_Sb=[4%dm
"endif

" Press space to clear search highlighting and any message already displayed.
nnoremap <silent> <Space> :silent noh<Bar>echo<CR>

set background=dark

" We kind of want color syntaxing in text mode too :-)
if &t_Co > 2 || has("gui_running")
	syntax on
endif

" Really fancy status line from Sven Guckes
" From http://www.vim.org/vimrc
set   statusline=Vim-%{Version()}\ %{getcwd()}\ \ %1*[%02n]%*\ %(%M%R%H%)\ %2*%F%*\ %=%{Options()}\ %3*<%l,%c%V>%*
" Text between "%{" and "%}" is being evaluated and thus suited for functions.
" Here I will use the function "Options()" as defined below to show the
" values of some (local) options..
" The strings "%N*" unto "%*" correspond to the highlight group "UserN":
"       User1: color for buffer number
  hi    User1 cterm=NONE    ctermfg=red    ctermbg=white  guifg=red    guibg=white
"       User2: color for filename
  hi    User2 cterm=NONE    ctermfg=black  ctermbg=green  guifg=black  guibg=green
"       User3: color for position
  hi    User3 cterm=NONE    ctermfg=blue   ctermbg=white  guifg=blue   guibg=white


set dictionary+=/usr/share/dict/words
"set encoding=utf-8 fileencodings=
