#!/bin/sh

# add to end of path
append_path()
{
  if ! eval test -z "\"\${$1##*:$2:*}\"" -o -z "\"\${$1%%*:$2}\"" -o -z "\"\${$1##$2:*}\"" -o -z "\"\${$1##$2}\"" ; then
    eval "$1=\$$1:$2"
  else
	eval "$1=$2"
  fi
}

# add to front of path
prepend_path()
{
  if ! eval test -z "\"\${$1##*:$2:*}\"" -o -z "\"\${$1%%*:$2}\"" -o -z "\"\${$1##$2:*}\"" -o -z "\"\${$1##$2}\"" ; then
    eval "$1=$2:\$$1"
  fi
}

{
	[ "$USER" = "rquattle" ] && {
		SHATTINGS_HISTORY=1
		SHATTINGS_TABS=1
	}
	[ "$USER" = "darco" ] && {
		SHATTINGS_HISTORY=1
		SHATTINGS_TABS=1
	}
}

[ "$SHATTINGS_HISTORY" = 1 ] && {
	shopt -s histappend
	export PROMPT_COMMAND='history -a && history -n'
	export HISTCONTROL="ignoredups"
	export HISTFILESIZE=2000
}

set mark-directories On
set mark-symlinked-directories On

set completion-ignore-case On

# Setup tabs
[ "$SHATTINGS_TABS" = 1 ] && {
	export TABWIDTH=4
	tabs -$TABWIDTH > /dev/null 2>&1
	alias less="less -x$TABWIDTH"
	export LS_COLWIDTHS=$TABWIDTH
}

if [ `uname` = "Darwin" ]
then
	# Grab any recently updated environment variables from launchd
	eval `launchctl export`

	append_path PATH /Developer/usr/bin
	append_path MANPATH /Developer/usr/share/man
	append_path MANPATH /Developer/Platforms/iPhoneOS.platform/usr/local/share/man

	[ -x ~/Applications/Development/GitX.app/Contents/Resources/gitx ] &&
		alias gitx=~/Applications/Development/GitX.app/Contents/Resources/gitx

	[ -x /Applications/GitX.app/Contents/Resources/gitx ] &&
		alias gitx=/Applications/GitX.app/Contents/Resources/gitx

	alias edit='xed'

	alias join='"/System/Library/Automator/Combine PDF Pages.action/Contents/Resources/join.py"'

	# make svn use opendiff
	export SVN_MERGE=~/.shattings/bin/svn-diff-wrapper
fi

# enable color support of ls and also add handy aliases
if [ "$TERM" != "dumb" ]
then
	ls --version > /dev/null 2>&1 && alias ls='ls --color=auto'

	# Have BSD 'ls' use GNU colors.
	export LSCOLORS=ExGxBxdxCxDxdxabagacad
	export CLICOLOR=1
fi

append_path PATH /bin
append_path PATH /sbin

append_path PATH /usr/bin
append_path PATH /usr/sbin
append_path MANPATH /usr/share/man
append_path PKG_CONFIG_PATH /usr/lib/pkgconfig

append_path PATH /usr/local/bin
append_path PATH /usr/local/sbin
append_path MANPATH /usr/local/share/man
append_path PKG_CONFIG_PATH /usr/local/lib/pkgconfig

append_path PATH /usr/X11R6/bin
append_path MANPATH /usr/X11R6/man
append_path PKG_CONFIG_PATH /usr/X11R6/lib/pkgconfig

append_path PATH /usr/X11/bin
append_path MANPATH /usr/X11/man

append_path PATH ~/.shattings/bin
append_path MANPATH ~/.shattings/share/man

prepend_path PATH ~/bin
prepend_path MANPATH ~/share/man
append_path PKG_CONFIG_PATH ~/lib/pkgconfig

# VIM-based 'less'
[ -x /usr/share/vim/vim72/macros/less.sh ] && VLESS='/usr/share/vim/vim72/macros/less.sh'
[ -x /usr/share/vim/vim73/macros/less.sh ] && VLESS='/usr/share/vim/vim73/macros/less.sh'

[ -x "$VLESS" ] && {
#	export PAGER="$VLESS"
	alias vless="$VLESS"
}

# DOSism...
alias "cd.."='cd ..'

if ( which vim 1>/dev/null )
then
export EDITOR="vim -n"
else
export EDITOR="vi"
fi

export LD_PREBIND=0
export PATH
export PKG_CONFIG_PATH
export MANPATH
export LIBRARY_PATH
export CPATH

# Enable fancy command line
. ~/.shattings/bash/ps1-git-svn.sh

# Enable GIT tab completion
. ~/.shattings/bash/git-completion.bash

. ~/.shattings/bash/man-completion.bash
