#!/bin/sh

TABWIDTH=4

shopt -s histappend

set completion-ignore-case on

# Setup tabs
tabs -$TABWIDTH
alias less="less -x$TABWIDTH"

# Enable fancy command line
. ~/.shattings/bash/ps1-git-svn.sh

# VIM-based 'less'
[ -x /usr/share/vim/vim72/macros/less.sh ] && alias vless='/usr/share/vim/vim72/macros/less.sh'
[ -x /usr/share/vim/vim73/macros/less.sh ] && alias vless='/usr/share/vim/vim73/macros/less.sh'

# Grab any recently updated environment variables from launchd
eval `launchctl export`

# define append_path and prepend_path to add directory paths, e.g. PATH, MANPATH.
# add to end of path
append_path()
{
  if ! eval test -z "\"\${$1##*:$2:*}\"" -o -z "\"\${$1%%*:$2}\"" -o -z "\"\${$1##$2:*}\"" -o -z "\"\${$1##$2}\"" ; then
    eval "$1=\$$1:$2"
  else
	eval "$1=$2"
  fi
}

# add to front of path
prepend_path()
{
  if ! eval test -z "\"\${$1##*:$2:*}\"" -o -z "\"\${$1%%*:$2}\"" -o -z "\"\${$1##$2:*}\"" -o -z "\"\${$1##$2}\"" ; then
    eval "$1=$2:\$$1"
  fi
}

[ -x ~/Applications/Development/GitX.app/Contents/Resources/gitx ] && alias gitx=~/Applications/Development/GitX.app/Contents/Resources/gitx
[ -x /Applications/GitX.app/Contents/Resources/gitx ] && alias gitx=/Applications/GitX.app/Contents/Resources/gitx

append_path MANPATH /usr/share/man
append_path MANPATH /usr/local/share/man
append_path MANPATH /Developer/usr/share/man
append_path MANPATH /Developer/Platforms/iPhoneOS.platform/usr/local/share/man

[ -r ~/bin ] && prepend_path PATH ~/bin

[ -r ~/lib/pkgconfig ] && append_path PKG_CONFIG_PATH ~/lib/pkgconfig
[ -r /usr/local/lib/pkgconfig ] && append_path PKG_CONFIG_PATH /usr/local/lib/pkgconfig
[ -r /usr/X11R6/lib/pkgconfig ] && append_path PKG_CONFIG_PATH /usr/X11R6/lib/pkgconfig
[ -r /usr/lib/pkgconfig ] && append_path PKG_CONFIG_PATH /usr/lib/pkgconfig

[ -r /usr/X11R6/bin ] && append_path PATH /usr/X11R6/bin
[ -r /usr/X11R6/man ] && append_path MANPATH /usr/X11R6/man
[ -r /usr/X11/bin ] && append_path PATH /usr/X11/bin
[ -r /usr/X11/man ] && append_path MANPATH /usr/X11/man

# DOSism...
alias "cd.."='cd ..'

alias edit='xed'

export LD_PREBIND=0
export EDITOR=vim
export SVN_MERGE=~/.shattings/bin/svn_diff_wrapper
export PATH
export PKG_CONFIG_PATH
export MANPATH
export LIBRARY_PATH
export CPATH

